version: '3.1'

services:
    app:
        build: .
        container_name: "app"
        hostname: "app"
        ports:
            - "9000:9000"
        environment:
            HTTP_PORT: 9000
            DB_PASS: secret
        depends_on:
            - postgres

    postgres:
        image: postgres
        restart: always
        container_name: postgres
        hostname: postgres
        environment:
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"